# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80af7acc2078823ab1375a6385b607f5"
name = "test-app-discount"
handle = "test-app-discount-7"
application_url = "https://updates-managing-islands-addresses.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://updates-managing-islands-addresses.trycloudflare.com/auth/callback",
  "https://updates-managing-islands-addresses.trycloudflare.com/auth/shopify/callback",
  "https://updates-managing-islands-addresses.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
